# Generated by Django 6.0.7 on 2026-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_seed_demo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='عام', max_length=100),
        ),
    ]
