# Generated by Django 6.0.7 on 2026-07-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentplan',
            name='next_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
