# Generated by Django 6.0.7 on 2026-07-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_installmentplan_next_due_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('phone', ''), _negated=True), fields=('phone',), name='unique_customer_phone_when_set'),
        ),
    ]
