# Generated by Django 6.0.7 on 2026-07-18 16:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_customer_unique_customer_phone_when_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('salaries', 'رواتب'), ('electricity', 'كهرباء'), ('rent', 'إيجار'), ('transportation', 'مواصلات'), ('maintenance', 'صيانة'), ('taxes', 'ضرائب'), ('other', 'أخرى')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_capital', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('dividends_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_profit_earned', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_loss_borne', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('last_dividend_payment_date', models.DateTimeField(blank=True, null=True)),
                ('distribution_method', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'كل 3 أشهر'), ('semi_annual', 'كل 6 أشهر'), ('annual', 'سنوي')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('withdrawn', 'منسحب')], default='active', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-current_capital'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_cogs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loss_policy', models.CharField(blank=True, choices=[('deduct_from_capital', 'تُخصم من رأس مال المستثمر'), ('record_only', 'تُسجَّل فقط دون خصم (تُعوَّض من أرباح لاحقة)'), ('owner_bears', 'يتحملها صاحب المشروع بالكامل')], default='', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-period_end', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('investment', 'استثمار أولي'), ('addition', 'إضافة استثمار'), ('withdrawal', 'سحب'), ('profit', 'ربح'), ('loss', 'خسارة'), ('dividend_payment', 'دفع أرباح مستحقة')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.investor')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvestorDistributionShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_percentage_snapshot', models.DecimalField(decimal_places=2, max_digits=6)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('capital_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('capital_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribution_shares', to='pos.investor')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='pos.profitdistribution')),
            ],
            options={
                'ordering': ['-share_amount'],
            },
        ),
    ]
