# Generated by Django 6.0.7 on 2026-07-22 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_expense_investor_profitdistribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investordistributionshare',
            name='investor_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='installmentplan',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_plans', to='pos.customer'),
        ),
        migrations.AlterField(
            model_name='investordistributionshare',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_shares', to='pos.investor'),
        ),
    ]
